// pet_app/backend/PetAdoptionAPI/Data/ApplicationDbContext.cs
using Microsoft.EntityFrameworkCore;
using PetAdoptionAPI.Models;

namespace PetAdoptionAPI.Data
{
    public class ApplicationDbContext : DbContext
    {
        // Constructor that passes options to the base DbContext
        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options) : base(options)
        {
        }

        // DbSet properties represent tables in the database
        public DbSet<Animal> Animals { get; set; }            // Animals table
        public DbSet<User> Users { get; set; }                // Users table
        public DbSet<AnimalSize> AnimalSizes { get; set; }    // Animal sizes table
        public DbSet<AnimalType> AnimalTypes { get; set; }    // Animal types table
        public DbSet<FosterHome> FosterHomes { get; set; }    // Foster homes table
        public DbSet<AdoptionRequest> AdoptionRequests { get; set; } // Adoption requests table
        public DbSet<Shelter> Shelters { get; set; }          // Shelters table
        public DbSet<Report> Reports { get; set; }            // Reports table
        public DbSet<AnimalImage> AnimalImages { get; set; }  // Animal images table

        // Configure model creation to set up PostgreSQL extensions and UUID defaults
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            // Register PostgreSQL extensions used for UUID generation and cryptography
            modelBuilder.HasPostgresExtension("uuid-ossp");
            modelBuilder.HasPostgresExtension("pgcrypto");

            // Configure UserId to be generated by PostgreSQL using uuid_generate_v4()
            modelBuilder.Entity<User>()
                .Property(u => u.UserId)
                .HasDefaultValueSql("uuid_generate_v4()");

            // Configure AnimalId to be generated by PostgreSQL using uuid_generate_v4()
            modelBuilder.Entity<Animal>()
                .Property(a => a.AnimalId)
                .HasDefaultValueSql("uuid_generate_v4()");

            // Configure FosterHomeId to be generated by PostgreSQL using uuid_generate_v4()
            modelBuilder.Entity<FosterHome>()
                .Property(f => f.FosterHomeId)
                .HasDefaultValueSql("uuid_generate_v4()");

            // Configure ShelterId to be generated by PostgreSQL using uuid_generate_v4()
            modelBuilder.Entity<Shelter>()
                .Property(s => s.ShelterId)
                .HasDefaultValueSql("uuid_generate_v4()");

            // Configure ReportId to be generated by PostgreSQL using uuid_generate_v4()
            modelBuilder.Entity<Report>()
                .Property(r => r.ReportId)
                .HasDefaultValueSql("uuid_generate_v4()");

            // Configure AdoptionRequestId to be generated by PostgreSQL using uuid_generate_v4()
            modelBuilder.Entity<AdoptionRequest>()
                .Property(ar => ar.AdoptionRequestId)
                .HasDefaultValueSql("uuid_generate_v4()");
        }
    }
}
